### ISSUE TITLE
Key error contig_699

### ISSUE THREAD

**Issue by lucast122** [rrwick/Rebaler#14]
Hello,

First of all I want to thank @rrwick for creating this tool, I use it in my pipeline to prepare assemblies for medaka correction.
I ran rebaler on three different flye assemblies from metagenome sequencings (minion). The first two times it worked perfectly fine, but for one sample it crashed at the final shred and polish stage.

Full traceback:

`Traceback (most recent call last):
  File "/Rebaler/rebaler-runner.py", line 9, in <module>
    main()
  File "/Rebaler/rebaler/__main__.py", line 97, in main
    final_assembly = final_shred_and_polish(ref_names, circularity, polish_dir, args.threads)
  File "/Rebaler/rebaler/__main__.py", line 180, in final_shred_and_polish
    polish_reads, threads, polish_dir, 2)
  File "/Rebaler/rebaler/__main__.py", line 396, in polish_assembly_with_racon
    unitig_graph = UnitigGraph(names, unpolished_sequences, circularity)
  File "/Rebaler/rebaler/unitig_graph.py", line 30, in __init__
    sequence = seqs[name]
KeyError: 'contig_699'`

I used python version 3.7 and the following line to call it

`python3.7 /Rebaler/rebaler-runner.py -t 48 assembly.fasta corrected_reads.fasta.gz > assembly_rebaler.fasta`

I checked the assembly file especially the contig_699 for any strange things but could not find something suspicious.
I hope this helps you in improving the software, if someone has any suggestions I would be happy to hear them.

**Comment by rrwick** [comment]
I think I've just fixed this one - it was a bug where Rebaler crashed when a contig was lost during the Racon polishing rounds. If you grab the fresh code from the main branch, it will now hopefully work!
