### ISSUE TITLE
Option for -l logfile

### ISSUE THREAD

**Issue by tseemann** [rrwick/Rebaler#2]
It would be great to save the log file for audit purposes.

Is there a way to remove the ANSI colour codes - they make the log unreadable.

**Comment by rrwick** [comment]
Here's a quick hack to get the ANSI codes out:
`sed -r 's|\x1B\[[0-9]{1,2}m||g' rebaler_log`

The better solution would certainly be to do something like you suggested: produce colourised output for the terminal and no-colour output into a log.

It's all doable, but are you using Rebaler enough for me to bother? 😄 Specifically, considering my answer to issue #3 (that Rebaler might not be the best choice for polishing a PacBio assembly), are you still going to use it? If so, and especially if you plan on using it a lot, then I'll try to improve its output (also addressing issue #1).

Ryan

**Comment by tseemann** [comment]
I was hoping to have a tool to do the polishing for me, one less thing to maintain. But I guess my dream has been quashed :)
