### ISSUE TITLE
racon v1.3.1

### ISSUE THREAD

**Issue by frchen47** [rrwick/Rebaler#4]
Hi, I feel that rebaler seems not compatible with racon v1.3.1.
It output the result very quick.
Polish       Assembly          Mapping
round            size          quality
begin       2,019,125      508,688,592

Best polish: temp_rebaler_23881/01_unpolished_assembly.fasta

Deleting temp directory temp_rebaler_23881
Thanks

frchen

**Comment by rrwick** [comment]
You are correct, Rebaler was broken with the new versions of Racon. I just made a new release of Rebaler (v0.1.1) which should fix it.

Thanks for letting me know!

Ryan

**Comment by frchen47** [comment]
Hi Ryan,
Thank you for your reply, however, I can not find any change in your code.
Thanks.
frchen

**Comment by rrwick** [comment]
I had made the change locally and failed to push it up to GitHub. How embarrassing! 😳 

I think I've fixed it up, so try the v0.1.1 release again. Sorry about that!

**Comment by frchen47** [comment]
It's fixed, I can use it. Thank you very much.

frchen
